"""The GSC contract shared by the SGX batch path: image naming + manifest.

``sgx-azure`` is batch-only, and the user's image is graminized **on the SGX VM**
by :func:`tee_crafter.cli.commands.deploy.batch.graminize_on_vm`, not on the
operator's machine.  That is not a preference: ``gsc`` never passes a platform to
``docker build`` (there is no ``platform`` anywhere in ``gsc.py``), so it
graminizes for the daemon's native architecture, and Gramine/SGX is x86-only — on
an arm64 workstation the local path silently produced an arm64 Gramine.  The VM
is amd64, has real SGX, and already carries the signing key baked in by
``scripts/sgx_azure/setup_sgx.sh``, so nothing private crosses the wire and
MRENCLAVE can be *measured* rather than recorded as a placeholder.

This module therefore holds only what both sides must agree on.  Getting any of
it wrong is silent rather than loud, which is why it lives in one place:

* ``gsc build <image> <manifest>`` — the second positional is a **manifest
  file**.  Passing an image name there (which this module used to do) yields
  ``Manifest file "..." does not exist``.
* ``gsc sign-image <image> <key>`` — **two** positionals, and ``<image>`` is the
  *original* app image, not the graminized one.
* GSC names its own outputs, ``gsc-<image>-unsigned`` then ``gsc-<image>``; a
  caller cannot choose them, and guessing meant re-saving a tarball from an
  image that did not exist.

There is **no non-enclave fallback**: if graminizing fails the deploy aborts
unless the operator sets ``TEE_CRAFTER_ALLOW_NON_ENCLAVE_SGX``.  Shipping the raw
OCI image means it runs as a plain process on the SGX VM — no enclave, no
MRENCLAVE, nothing to attest — and the run used to report success anyway.
"""
from __future__ import annotations

import logging
import os
from tee_crafter.core.env_flags import env_hatch_open

logger = logging.getLogger(__name__)

#: Default enclave size.  Must be a power of two and larger than the workload's
#: peak RSS, or the enclave dies at runtime with an out-of-EPC abort.  4G matches
#: GSC's own ``test/generic.manifest`` default.
DEFAULT_ENCLAVE_SIZE = "4G"
#: Gramine pre-creates every thread slot, so this is a ceiling, not a hint.
DEFAULT_MAX_THREADS = 64

ENCLAVE_SIZE_ENV = "TEE_CRAFTER_SGX_ENCLAVE_SIZE"
MAX_THREADS_ENV = "TEE_CRAFTER_SGX_MAX_THREADS"

#: Explicit opt-in to shipping a **non-enclave** SGX run.  Lives here rather than
#: in the deploy flow because the gate itself moved to the VM
#: (``batch.graminize_on_vm``): whoever enforces it should read the flag from the
#: same module that owns the GSC contract.
ALLOW_NON_ENCLAVE_SGX_ENV = "TEE_CRAFTER_ALLOW_NON_ENCLAVE_SGX"


def non_enclave_sgx_allowed() -> bool:
    """Whether the operator has accepted running SGX *outside* an enclave."""
    return env_hatch_open(ALLOW_NON_ENCLAVE_SGX_ENV)


def gsc_unsigned_image_name(image_tag: str) -> str:
    """Mirror of GSC's own ``gsc_unsigned_image_name``."""
    return f"gsc-{image_tag}-unsigned"


def gsc_signed_image_name(image_tag: str) -> str:
    """Mirror of GSC's own ``gsc_image_name``.

    GSC derives both names from the *original* image tag; nothing lets a caller
    choose them.  Guessing a different name is how this module previously
    reported a graminized image that did not exist.
    """
    return f"gsc-{image_tag}"


def build_manifest(
    *, enclave_size: str | None = None, max_threads: int | None = None,
) -> str:
    """Render the partial Gramine manifest that ``gsc build`` merges.

    ``gsc build`` takes a manifest **file**, not an output image name, and the
    file is a *fragment*: GSC merges it over
    ``templates/entrypoint.common.manifest.template``, which already supplies
    the entrypoint, mounts and library paths derived from the image itself.  So
    this only needs to carry what GSC cannot infer — enclave geometry and the
    attestation mode.

    ``sgx.remote_attestation = "dcap"`` is set because MRENCLAVE-based remote
    attestation is the entire purpose of this platform; Azure SGX (DCsv3) is a
    DCAP/ECDSA environment, not EPID (EPID was deprecated by Intel and is not
    offered on Azure's confidential SKUs).
    """
    size = enclave_size or os.environ.get(ENCLAVE_SIZE_ENV) or DEFAULT_ENCLAVE_SIZE
    threads = max_threads or _env_int(MAX_THREADS_ENV) or DEFAULT_MAX_THREADS
    return (
        "# Generated by TEE-Crafter for `gsc build`; merged over GSC's own\n"
        "# entrypoint manifest template.  Fragment, not a full manifest.\n"
        f'sgx.enclave_size = "{size}"\n'
        f"sgx.max_threads = {threads}\n"
        'sgx.remote_attestation = "dcap"\n'
        "\n"
        "# **Nothing about the batch input/output paths belongs in this\n"
        "# fragment.** They are declared after `gsc build`, by\n"
        "# `manifest_patch_command()` below.  This is not a style choice -- a\n"
        "# path named here cannot work at all, and the reason is worth stating\n"
        "# because two separate revisions of this file got it wrong:\n"
        "#\n"
        "# GSC's `finalize_manifest.py` reads *three* keys out of the fragment\n"
        "# -- `sgx.trusted_files`, `sgx.allowed_files` AND\n"
        "# `sgx.protected_files` -- and pushes all of them through the same\n"
        "# expansion (finalize_manifest.py:48-55 and :38-46 at the pinned\n"
        "# commit)::\n"
        "#\n"
        "#   already_added_files = extract_files_from_user_manifest(...)\n"
        "#   rendered['sgx']['trusted_files'] = \\\n"
        "#       expand_trusted_files(trusted_files + already_added_files)\n"
        "#   ...\n"
        "#   if file_path.exists(): ...compute_sha256(file_path)\n"
        "#   else: raise ManifestError(f'File not found: {file_path}')\n"
        "#\n"
        "# So an `allowed_files` entry is (a) required to exist in the image at\n"
        "# build time and (b) *hashed into `trusted_files`* if it does -- which\n"
        "# would defeat the point twice over, since a measured input then has\n"
        "# to match that hash at run time.  `/input` is a docker bind mount\n"
        "# (`-v /var/lib/tee_crafter/input:/input:ro`) and cannot exist at\n"
        "# build time by construction, so the build simply dies::\n"
        "#\n"
        "#   NameError: name 'ManifestError' is not defined\n"
        "#\n"
        "# That `NameError` is a bug in GSC itself -- `ManifestError` is never\n"
        "# defined in the module -- so the exception that would have named the\n"
        "# missing path is replaced by one that does not.  Reproduced on real\n"
        "# SGX hardware on 2026-08-23 with `allowed_files` as the only\n"
        "# declaration and no mount at all, which is what identified\n"
        "# `allowed_files` rather than `fs.mounts` as the cause.  (An earlier\n"
        "# revision of this comment blamed `fs.mounts`; finalize_manifest.py\n"
        "# never looks at `fs.mounts`.)\n"
    )


#: Host-visible paths the batch flow needs inside the enclave.  ``/input`` is
#: the read-only bind mount carrying this run's data; ``/output`` is where the
#: workload writes results, which the batch flow then captures with
#: ``docker diff`` + ``docker cp``.
BATCH_ALLOWED_PATHS = ("file:/input", "file:/output")

#: Path of the finalized manifest inside the graminized image.
_FINALIZED_MANIFEST = "/gramine/app_files/entrypoint.manifest"


def manifest_patch_dockerfile(unsigned_image: str, app_user: str = "") -> str:
    """Dockerfile that declares the batch I/O paths *after* ``gsc build``.

    ``gsc build`` finalizes the manifest -- walking the image and recording a
    sha256 for every file it measures -- and ``gsc sign-image`` then only runs
    ``gramine-sgx-sign`` over whatever manifest it finds
    (templates/Dockerfile.common.sign.template).  It does **not** re-run
    finalize.  That gap is what makes this work: inserting the declaration
    between the two steps keeps GSC's measured ``trusted_files`` for all of the
    application's own code, and MRENCLAVE still covers the insertion, because
    the signature is computed over the patched manifest.  So the allowance is
    itself attested rather than smuggled in.

    Honest about the cost: Gramine prints this on every run, and it is
    accurate::

        Gramine detected the following insecure configurations:
          - sgx.allowed_files = [ ... ]   (some files are passed through from
                                           untrusted host without verification)
        Gramine will continue application execution, but this configuration
        must not be used in production!

    The enclave does not verify the input; the run's integrity claim for it
    rests on the input digest recorded in the signed audit trail, and the
    output is written to host-visible storage in the clear (inherent to
    ``docker diff`` capture).  Measuring the input instead is possible -- its
    hash is known at deploy time -- but makes MRENCLAVE change with every
    input, which is why this project does not: the pinned measurement is meant
    to be comparable across runs.

    The insert is guarded on the manifest's first line actually being
    ``[sgx]`` (tomli_w writes the table header first, then the scalar keys,
    then the ``[[sgx.trusted_files]]`` tables) so a GSC change in layout fails
    the build loudly instead of silently corrupting a signed manifest.

    ``app_user`` is the image's own ``Config.User``, restored at the end.  The
    sign stage is ``FROM <unsigned>`` and only copies the signature back
    (Dockerfile.common.sign.template), so a ``USER root`` left behind here
    would silently promote the workload to root in the *signed* image.

    Returned as Dockerfile text rather than a shell one-liner on purpose: the
    TOML needs double-quoted strings, the ``sed`` script needs single quotes
    around them, and the whole thing then has to survive an ``ssh`` argv and a
    ``sh -c``.  An earlier version built this as nested shell quoting and the
    inner double quotes collapsed, which would have written
    ``allowed_files = [ file:/input, file:/output ]`` -- invalid TOML, and
    caught only because the rendered command was read before it ran.  The
    caller base64s this, exactly like the build fragment.
    """
    lines = [
        f"FROM {unsigned_image}",
        "USER root",
        (f"RUN head -1 {_FINALIZED_MANIFEST} | grep -qx '\\[sgx\\]' "
         f"&& sed -i '1a allowed_files = [ "
         + ", ".join(f'"{p}"' for p in BATCH_ALLOWED_PATHS)
         + f" ]' {_FINALIZED_MANIFEST} "
         f"&& grep -q '^allowed_files' {_FINALIZED_MANIFEST}"),
    ]
    if app_user.strip():
        lines.append(f"USER {app_user.strip()}")
    return "\n".join(lines) + "\n"


def _env_int(name: str) -> int | None:
    raw = os.environ.get(name, "").strip()
    if not raw:
        return None
    try:
        return int(raw)
    except ValueError:
        logger.warning("ignoring non-integer %s=%r", name, raw)
        return None
