"""Markdown compliance report renderer."""
from __future__ import annotations

import os
from typing import Any, Dict, List


_STATUS_ICON = {
    "satisfied": "PASS",
    "partial": "PARTIAL",
    "gap": "GAP",
    "not_applicable": "N/A",
    "customer_responsibility": "CUSTOMER",
}


def render_markdown(report_data: Dict[str, Any], compliance_dir: str) -> str:
    """Write compliance_report.md. Returns the file path."""
    lines: List[str] = []
    _header(lines, report_data)
    _summary(lines, report_data)
    _evidence_inventory(lines, report_data)

    for fw_id, fw_data in report_data.get("frameworks", {}).items():
        _framework_section(lines, fw_id, fw_data)

    lines.append("")
    lines.append("---")
    lines.append("*Generated by TEE-Crafter Compliance Engine. "
                 "This report reflects product-level evidence only. "
                 "See docs/compliance.md for full coverage roadmap.*")
    lines.append("")

    path = os.path.join(compliance_dir, "compliance_report.md")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    return path


def _header(lines: List[str], data: Dict[str, Any]) -> None:
    lines.append("# TEE-Crafter Compliance Report")
    lines.append("")
    lines.append(f"- **Report ID:** `{data['report_id']}`")
    lines.append(f"- **Generated:** {data['generated_at']}")
    lines.append(f"- **Platform:** {data['deployment']['tee_platform']}")
    lines.append(f"- **Flow:** {data['deployment']['flow']}")
    lines.append(f"- **Cloud:** {data['deployment']['cloud']}")
    prov = data["provenance"]
    lines.append(f"- **Provenance chain valid:** {prov['chain_valid']}")
    lines.append(f"- **Provenance signature valid:** {prov['signature_valid']}")
    lines.append(f"- **Chain head hash:** `{prov['chain_head_hash'][:16]}...`")
    lines.append("")


def _summary(lines: List[str], data: Dict[str, Any]) -> None:
    s = data["summary"]
    lines.append("## Summary")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Frameworks evaluated | {s['frameworks_evaluated']} |")
    lines.append(f"| Total controls | {s['total_controls']} |")
    lines.append(f"| Satisfied | {s['by_status']['satisfied']} |")
    lines.append(f"| Partial | {s['by_status']['partial']} |")
    lines.append(f"| Gap | {s['by_status']['gap']} |")
    lines.append(f"| Not applicable | {s['by_status']['not_applicable']} |")
    lines.append(f"| Customer responsibility | {s['by_status']['customer_responsibility']} |")
    lines.append(f"| Product coverage | {s['product_coverage_pct']}% |")
    lines.append(f"| Overall coverage | {s['overall_coverage_pct']}% |")
    lines.append("")


def _evidence_inventory(lines: List[str], data: Dict[str, Any]) -> None:
    inv = data.get("evidence_inventory", [])
    if not inv:
        return
    lines.append("## Evidence Inventory")
    lines.append("")
    lines.append("| Evidence Key | Collected | Strength |")
    lines.append("|-------------|-----------|----------|")
    for e in inv:
        lines.append(f"| {e['key']} | {e['collected']} | {e['strength']} |")
    lines.append("")


def _framework_section(lines: List[str], fw_id: str, fw_data: Dict[str, Any]) -> None:
    lines.append(f"## {fw_data['name']} ({fw_data['version']})")
    lines.append("")
    lines.append(f"*Tier: {fw_data['tier']} | "
                 f"Controls: {fw_data['controls_evaluated']} | "
                 f"Satisfied: {fw_data['satisfied']} | "
                 f"Partial: {fw_data['partial']} | "
                 f"Gap: {fw_data['gap']}*")
    lines.append("")
    lines.append("| Control | Title | Status | Responsibility | Notes |")
    lines.append("|---------|-------|--------|---------------|-------|")

    for c in fw_data.get("controls", []):
        status = _STATUS_ICON.get(c["status"], c["status"])
        resp = c.get("responsibility", "")
        notes = c.get("notes", "").replace("|", "/").replace("\n", " ")
        if len(notes) > 100:
            notes = notes[:97] + "..."
        ca = c.get("customer_action", "")
        if ca:
            notes += f" **Action:** {ca[:60]}"
            if len(ca) > 60:
                notes += "..."
        lines.append(f"| {c['control_id']} | {c['title']} | {status} | {resp} | {notes} |")

    lines.append("")
