"""NitroTPM attestation documents, for measurement-gated ``kms:Decrypt``.

Why this exists
---------------
``snp-aws`` key release used to be identity-gated and nothing more: the gate was
"does the caller's principal ARN equal the per-deploy instance role", which says
who is asking and not what they are running.  See
:mod:`tee_crafter.core.keys.gating` for the full truth table.

AWS KMS *does* offer a measurement-bound alternative on ordinary EC2 instances,
not only inside Nitro Enclaves.  The condition keys are
``kms:RecipientAttestation:NitroTPMPCR<n>``, and the KMS documentation states the
requirement precisely:

    This condition key is effective only when the ``Recipient`` parameter in the
    request specifies a signed attestation document from NitroTPM. [...] If the
    request does not include an attestation document, permission is denied
    because this condition is not satisfied.

    -- docs.aws.amazon.com/kms/latest/developerguide/conditions-nitro-tpm.html

Read that carefully, because the distinction drives this whole module: what KMS
requires is *a signed attestation document*, not an "Attestable AMI".  An
Attestable AMI is how AWS makes PCR values **predictable ahead of time**, by
building the image from a KIWI NG image description on Amazon Linux 2023 and
precomputing the UKI's PCRs with ``nitro-tpm-pcr-compute``.  TEE-Crafter does not
need to predict them: it already boots each baked image and records what it
observes, which is how every other platform's measurement reaches the registry.
So the AL2023/KIWI pipeline is avoidable; the signed document is not.

    An Attestation Document is generated by the NitroTPM and it is signed by the
    Nitro Hypervisor.

    -- docs.aws.amazon.com/AWSEC2/latest/UserGuide/nitrotpm-attestation-document-content.html

That sentence is also why this path needs no trust anchor of its own.  KMS is the
verifier; it validates the hypervisor's signature and the PCR values before it
will decrypt.

There is, however, a second route, and an earlier version of this docstring was
wrong to rule it out.  It claimed ``certs/nitro-root.pem`` "endorses a different
key hierarchy", so a NitroTPM document could only be checked by delegating to
KMS.  Measured on 2026-08-24 against a real document, the opposite is true: the
``cabundle`` roots at ``CN=aws.nitro-enclaves``, byte-for-byte the certificate
this repository already pins, and the whole chain plus the COSE_Sign1 signature
verifies locally.  :func:`verify_document_locally` does that, which is what lets
``gpu-cc-aws`` verify CPU evidence client-side with the trust root in this
repository rather than delegated to AWS.

Which PCRs to pin
-----------------
AWS documents PCR4, PCR7 and PCR12 as the ones that validate the launch, and
they are not interchangeable:

* **PCR7 -- Secure Boot Policy.**  A hash of the instance's UEFI Secure Boot
  policy.  The ``snp-aws`` bake enrols a Platform Key, KEK and ``db`` into the
  AMI's ``UefiData`` (see ``cli/commands/baking/snp.py``), so this value is
  fixed by the AMI and stable across reboots.  On its own it proves "booted
  under our Secure Boot policy" -- **not** "booted this exact image", because
  any AMI carrying the same certificates produces the same PCR7.  AWS says as
  much: holding a policy against PCR7 alone still lets instances launched from
  older AMIs with the same certificate pass.
* **PCR4 -- Boot Manager Code.**  Hashes of the binaries the UEFI environment
  executed.  This is the value that makes the gate image-specific, and it moves
  whenever the boot chain does (a kernel or bootloader update in a new bake).
* **PCR12 -- kernel command line.**  Needed alongside PCR4 for standard boot;
  cheap to add and it closes "same binaries, different cmdline".

Hence :data:`DEFAULT_PINNED_PCRS` is ``(4, 7)``: PCR4 for image identity, PCR7
for Secure Boot policy.  Pinning PCR7 alone would be weaker than it looks, and
saying so in a docstring is cheaper than someone discovering it from a policy.

The response is CMS, not raw RSA
--------------------------------
``CiphertextForRecipient`` is a CMS (RFC 5652) ``EnvelopedData`` structure, the
same shape the Nitro Enclaves flow already returns -- AWS's own example decrypts
it with ``openssl cms -decrypt``, not with a raw OAEP operation.  A consumer that
reads ``KeyEncryptionAlgorithm=RSAES_OAEP_SHA_256`` and performs a single RSA
decrypt will fail on the symmetric layer.  :func:`decrypt_ciphertext_for_recipient`
does the two-step properly, reusing the parser already proven on ``nitro-aws``.
"""
from __future__ import annotations

import os
import subprocess
from typing import Any, Dict, Iterable, Optional, Sequence, Tuple

#: Where the bake installs AWS's utility.  It is a Rust binary from
#: github.com/aws/NitroTPM-Tools; that repository ships a Docker-based
#: static-link builder ("For static linking requirements, a Docker-based build
#: environment is provided"), which is what makes it usable on the Ubuntu image
#: this project bakes rather than only on Amazon Linux 2023 where it is a yum
#: package (``aws-nitro-tpm-tools``).
NITRO_TPM_ATTEST_BIN = os.environ.get(
    "TEE_CRAFTER_NITRO_TPM_ATTEST_BIN", "/usr/bin/nitro-tpm-attest")

#: PCR meanings, from the AWS attestation-document contents page.
PCR_BOOT_MANAGER_CODE = 4
PCR_SECURE_BOOT_POLICY = 7
PCR_KERNEL_CMDLINE = 12

#: See the module docstring: PCR4 for image identity, PCR7 for Secure Boot
#: policy.  PCR12 is available but not on by default -- it only adds value
#: alongside PCR4 for standard boot, and every ``snp-aws`` bake enrols Secure
#: Boot.
DEFAULT_PINNED_PCRS: Tuple[int, ...] = (PCR_BOOT_MANAGER_CODE,
                                        PCR_SECURE_BOOT_POLICY)

#: PCR0 and PCR1 are AWS-controlled and documented as holding *constant* values
#: so that early boot code can be updated safely.  Pinning them would look like
#: a tighter policy while adding nothing an attacker has to defeat.
_CONSTANT_AWS_PCRS = frozenset({0, 1})

#: The PCR bank a NitroTPM attestation document reports, and therefore the only
#: bank whose values KMS will match. The document's ``digest`` field says
#: ``SHA384``; see :func:`read_pcrs`.
PCR_BANK = "sha384"

#: KMS accepts a lower-case hex string of up to 96 bytes per PCR. SHA-384 PCRs
#: are 48 bytes (96 hex chars), comfortably inside that.
_MAX_PCR_HEX_LEN = 96 * 2


class NitroTpmError(RuntimeError):
    """The NitroTPM attestation document could not be produced."""


def condition_key(pcr_id: int) -> str:
    """Return the KMS condition key name for *pcr_id*.

    >>> condition_key(7)
    'kms:RecipientAttestation:NitroTPMPCR7'
    """
    return f"kms:RecipientAttestation:NitroTPMPCR{int(pcr_id)}"


def validate_pcr_selection(pcrs: Iterable[int]) -> Tuple[int, ...]:
    """Return *pcrs* as a sorted tuple, refusing selections that prove nothing.

    Rejects an empty selection (a policy with no PCR condition is an identity
    check wearing an attestation costume) and the AWS-constant registers.
    """
    selected = sorted({int(p) for p in pcrs})
    if not selected:
        raise NitroTpmError(
            "no PCRs selected: a NitroTPM key policy with no PCR condition is "
            "identity-gated, which is the state this path exists to replace")
    constant = [p for p in selected if p in _CONSTANT_AWS_PCRS]
    if constant:
        raise NitroTpmError(
            f"PCR{constant[0]} is documented by AWS as holding a constant "
            "value so early boot code can be updated safely, so pinning it "
            "tightens nothing. Pin PCR4 (boot manager code) and PCR7 (Secure "
            "Boot policy) instead.")
    return tuple(selected)


def validate_pcr_value(pcr_id: int, value: str) -> str:
    """Return *value* normalised to the form KMS expects, or raise.

    KMS requires "a lower-case hexadecimal string of up to 96 bytes".  A policy
    written with an upper-case digest still *matches* under
    ``StringEqualsIgnoreCase``, but normalising here means the recorded policy
    and the recorded measurement compare equal as strings, which is what the
    evidence layer diffs.
    """
    text = (value or "").strip().lower()
    if not text:
        raise NitroTpmError(f"PCR{pcr_id} has no recorded value")
    if len(text) > _MAX_PCR_HEX_LEN:
        raise NitroTpmError(
            f"PCR{pcr_id} value is {len(text) // 2} bytes; KMS accepts at most "
            "96 bytes")
    if len(text) % 2 or any(c not in "0123456789abcdef" for c in text):
        raise NitroTpmError(
            f"PCR{pcr_id} value is not an even-length hex string: {value!r}")
    if len(text) == 64:
        # 32 bytes is a SHA-256 read, and it is the one wrong answer that looks
        # completely right. Cost of not catching it, measured on live KMS
        # 2026-08-24: the conditional Allow never matches, authorisation falls
        # through to the account-root delegation, and the deploy reports
        # kms-enforced while enforcing nothing.
        raise NitroTpmError(
            f"PCR{pcr_id} value is 32 bytes, which is a {PCR_BANK.replace('384','256')} "
            f"digest. NitroTPM attestation documents report digest=SHA384 and "
            f"KMS matches against those 48-byte values, so a SHA-256 read never "
            f"matches. Read the {PCR_BANK} bank "
            f"(tpm2_pcrread {PCR_BANK}:4,7).")
    return text


def generate_recipient_keypair(key_size: int = 2048):
    """Return ``(private_key, public_key_der)`` for the ``Recipient`` envelope.

    RSA specifically: the ``nitro-tpm-attest`` ``--public-key`` parameter is
    documented as "Only RSA keys are supported", and KMS's
    ``KeyEncryptionAlgorithm`` for this flow is ``RSAES_OAEP_SHA_256``.  The
    public half is returned DER-encoded because that is the form AWS's own
    example feeds the utility (``openssl rsa -pubout -outform DER``).
    """
    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.primitives.asymmetric import rsa

    private_key = rsa.generate_private_key(public_exponent=65537,
                                           key_size=key_size)
    public_der = private_key.public_key().public_bytes(
        encoding=serialization.Encoding.DER,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )
    return private_key, public_der


def attestation_document(
    public_key_der: bytes,
    *,
    nonce: Optional[bytes] = None,
    user_data: Optional[bytes] = None,
    binary: str = "",
    timeout: int = 30,
    runner=None,
) -> bytes:
    """Return a signed NitroTPM attestation document as raw CBOR/COSE bytes.

    *public_key_der* is embedded in the document, and KMS encrypts
    ``CiphertextForRecipient`` to it.  The document is **not** base64-encoded
    here: boto3 accepts raw bytes for ``Recipient.AttestationDocument`` and does
    its own encoding, exactly as the existing Nitro Enclaves path does.

    *nonce* and *user_data* are accepted because the utility takes them and a
    non-KMS verifier needs them, but AWS documents both as "Not used for
    attestation with AWS KMS", so callers on the KMS path should leave them
    unset rather than assume KMS binds them.

    Raises :class:`NitroTpmError` on any failure.  There is deliberately no
    fallback to an unattested ``kms:Decrypt``: silently degrading a
    measurement-gated release to an identity-gated one would defeat the point,
    and the caller cannot tell the difference from the plaintext.
    """
    if not public_key_der:
        raise NitroTpmError(
            "a recipient public key is required: without it KMS returns "
            "Plaintext rather than CiphertextForRecipient, and the key "
            "material would cross the wire outside the TEE's control")

    exe = binary or NITRO_TPM_ATTEST_BIN
    run = runner or subprocess.run

    # Files rather than argv: the utility takes paths, and a DER public key is
    # binary so it cannot be passed as an argument at all.
    import tempfile

    with tempfile.TemporaryDirectory(prefix="nitrotpm-") as tmp:
        argv = [exe]
        for flag, blob in (("--public-key", public_key_der),
                           ("--nonce", nonce),
                           ("--user-data", user_data)):
            if blob is None:
                continue
            path = os.path.join(tmp, flag.lstrip("-"))
            with open(path, "wb") as handle:
                handle.write(blob)
            argv += [flag, path]

        try:
            completed = run(argv, capture_output=True, timeout=timeout)
        except FileNotFoundError as exc:
            raise NitroTpmError(
                f"{exe} not found. NitroTPM attestation needs AWS's "
                "nitro-tpm-attest utility baked into the image, and the AMI "
                "must have been registered with TpmSupport=v2.0 -- CreateImage "
                "cannot set that, so an AMI captured from a running instance "
                "reports TpmSupport: null.") from exc
        except subprocess.TimeoutExpired as exc:
            raise NitroTpmError(
                f"{exe} did not return within {timeout}s") from exc

    if completed.returncode != 0:
        stderr = (completed.stderr or b"").decode("utf-8", "replace").strip()
        raise NitroTpmError(
            f"{exe} exited {completed.returncode}: "
            f"{stderr or '<no stderr>'}")

    document = completed.stdout or b""
    if not document:
        raise NitroTpmError(f"{exe} exited 0 but produced no document")
    return document


def decrypt_ciphertext_for_recipient(ciphertext: bytes, private_key) -> bytes:
    """Decrypt a KMS ``CiphertextForRecipient`` CMS envelope.

    Two layers, not one: an RSA-OAEP-SHA-256 encrypted content-encryption key,
    then AES over the content.  AWS's own worked example uses
    ``openssl cms -decrypt``; doing a single RSA operation on this blob fails.
    """
    if not ciphertext:
        raise NitroTpmError("CiphertextForRecipient was empty")
    try:
        from asn1crypto import cms as asn1_cms
    except ImportError as exc:  # pragma: no cover - present in the baked image
        raise NitroTpmError(
            "asn1crypto is required to parse the CMS envelope KMS returns in "
            "CiphertextForRecipient") from exc

    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.asymmetric import padding
    from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM

    info = asn1_cms.ContentInfo.load(ciphertext)
    enveloped = info["content"]
    recipient = enveloped["recipient_infos"][0].chosen

    cek = private_key.decrypt(
        recipient["encrypted_key"].native,
        padding.OAEP(mgf=padding.MGF1(algorithm=hashes.SHA256()),
                     algorithm=hashes.SHA256(), label=None),
    )

    enc_info = enveloped["encrypted_content_info"]
    algo = enc_info["content_encryption_algorithm"]
    body = enc_info["encrypted_content"].native
    # asn1crypto decodes the mode and IV/nonce for us; reading
    # ``parameters.native`` directly gets this wrong, because the parameter
    # shape differs between CBC and GCM.
    mode = algo.encryption_mode
    iv = algo.encryption_iv

    if mode == "gcm":
        return AESGCM(cek).decrypt(iv, body, None)
    if mode != "cbc":
        raise NitroTpmError(
            f"unsupported CMS content encryption mode {mode!r} "
            f"(algorithm {algo['algorithm'].native}, "
            f"OID {algo['algorithm'].dotted})")

    decryptor = Cipher(algorithms.AES(cek), modes.CBC(iv)).decryptor()
    padded = decryptor.update(body) + decryptor.finalize()
    if not padded:
        raise NitroTpmError("CBC decryption produced no output")
    pad_len = padded[-1]
    if pad_len < 1 or pad_len > 16 or len(padded) < pad_len:
        raise NitroTpmError(f"invalid PKCS#7 padding length {pad_len}")
    if any(byte != pad_len for byte in padded[-pad_len:]):
        raise NitroTpmError("invalid PKCS#7 padding bytes")
    return padded[:-pad_len]


def read_pcrs(pcrs: Sequence[int] = DEFAULT_PINNED_PCRS,
              runner=None, timeout: int = 15) -> Dict[str, str]:
    """Read *pcrs* from the local TPM with ``tpm2_pcrread``.

    Returns ``{"4": "<hex>", "7": "<hex>"}``.  The bake uses this to record
    reference values; the runtime uses it for the advisory measurement in
    :class:`~tee_crafter.core.keys.attestation_providers.NitroTpmAttestationProvider`.

    This is **not** the enforcing read.  A PCR value read out of the guest is
    only as trustworthy as the guest, which is why the value that gates key
    release is the one inside the hypervisor-signed attestation document, checked
    by KMS.  Reading them here is how we learn what to *write into the policy*,
    and a bake-time read is trustworthy for that purpose in the same way every
    other measurement in this project's registry is: it was observed on a machine
    booted from the image we just built.

    **The bank matters and it is not SHA-256.** A NitroTPM attestation document
    reports ``digest: SHA384`` and carries 48-byte PCR values; KMS compares its
    ``kms:RecipientAttestation:NitroTPMPCR<n>`` condition against *those*. Read
    with ``sha256:`` and you get 32-byte values that look entirely plausible,
    never match, and -- because a conditional Allow that fails to match simply
    falls through to another statement -- produce a key policy that appears to
    gate on a measurement while gating on nothing. Confirmed on hardware
    2026-08-24 by decoding a real document: PCR4 came back 48 bytes and did not
    resemble the SHA-256 read of the same register on the same boot.

    ``tpm2_pcrread`` output is a YAML-ish block, one selection per bank::

        sha384:
          4 : 0x5A3F834B...
          7 : 0x5DDAEB81...
    """
    selected = validate_pcr_selection(pcrs)
    run = runner or subprocess.run
    spec = f"{PCR_BANK}:" + ",".join(str(p) for p in selected)
    try:
        completed = run(["tpm2_pcrread", spec], capture_output=True,
                        timeout=timeout)
    except FileNotFoundError as exc:
        raise NitroTpmError(
            "tpm2_pcrread not found; the bake installs tpm2-tools for this") from exc
    except subprocess.TimeoutExpired as exc:
        raise NitroTpmError(f"tpm2_pcrread did not return within {timeout}s") from exc

    if completed.returncode != 0:
        stderr = (completed.stderr or b"").decode("utf-8", "replace").strip()
        raise NitroTpmError(f"tpm2_pcrread exited {completed.returncode}: {stderr}")

    out: Dict[str, str] = {}
    text = (completed.stdout or b"").decode("utf-8", "replace")
    for line in text.splitlines():
        if ":" not in line:
            continue
        left, _, right = line.partition(":")
        index, value = left.strip(), right.strip()
        if not index.isdigit():
            continue
        if value.lower().startswith("0x"):
            value = value[2:]
        try:
            out[index] = validate_pcr_value(int(index), value)
        except NitroTpmError:
            continue

    missing = [str(p) for p in selected if str(p) not in out]
    if missing:
        raise NitroTpmError(
            f"tpm2_pcrread returned no value for PCR{', PCR'.join(missing)}; "
            f"output was: {text.strip()[:200]}")
    return out


def verify_document_via_kms(kms_client, document: bytes,
                            number_of_bytes: int = 32) -> Dict[str, Any]:
    """Ask AWS KMS whether *document* is a genuine NitroTPM attestation.

    Returns a dict with ``verified``, ``verifier`` and ``detail``.  Raises
    nothing on a negative verdict -- the verdict is the return value -- but does
    raise :class:`NitroTpmError` if the call itself could not be made.

    Why this exists
    ---------------
    This is a *second opinion*, not the only route.  It was written when the
    belief was that a NitroTPM document could not be checked locally, because
    ``certs/nitro-root.pem`` is the Nitro *Enclaves* root and was assumed to
    endorse a different key hierarchy.  Measured 2026-08-24: it does not -- a
    NitroTPM document's ``cabundle`` roots at that exact certificate, so
    :func:`verify_document_locally` verifies it with no help from AWS.

    Keep this function anyway.  It is what proves a document is acceptable *to
    KMS specifically*, which is the thing that matters before relying on
    ``kms:RecipientAttestation:NitroTPMPCR<n>`` conditions for key release: KMS
    enforces its own freshness window (five minutes, measured) and its own
    parsing, and a document this repository is happy with is not automatically
    one KMS will accept.  Useful as a preflight check and as an independent
    cross-check of the local verifier.

    ``kms:GenerateRandom``
    accepts a ``Recipient`` carrying a NitroTPM attestation document, and the API
    reference is explicit about when the answer comes back:

        This field [CiphertextForRecipient] is included in the response only
        when the ``Recipient`` parameter in the request includes a **valid**
        attestation document from an AWS Nitro enclave or NitroTPM.

        -- docs.aws.amazon.com/kms/latest/APIReference/API_GenerateRandom.html

    ``GenerateRandom`` is the right operation for a pure attestation check
    because it touches no key material at all: it takes no ``KeyId``, AWS
    documents it as using "no account-specific resources, such as KMS keys", and
    the only permission needed is ``kms:GenerateRandom``.  Attach
    ``kms:RecipientAttestation:NitroTPMPCR4`` / ``PCR7`` conditions to that IAM
    permission and a success additionally means the PCRs matched.

    What this does and does not prove
    ---------------------------------
    It proves the document was signed by the Nitro Hypervisor and, where PCR
    conditions are attached, that the measured boot matches.  It does **not**
    move the trust root into this repository: the root becomes AWS KMS.  That is
    a delegation, and it is the same shape as ``tdx-azure`` trusting Microsoft
    Azure Attestation rather than Intel DCAP -- an accepted pattern here, but one
    that should be stated rather than glossed, which is why the returned dict
    names the verifier.

    Note the asymmetry that makes this usable from a *client*: the caller does
    not need to decrypt anything.  ``CiphertextForRecipient`` is encrypted to the
    public key inside the document -- the attested instance's key, not ours -- so
    a verifier consumes KMS's verdict, not the random bytes.  A caller that also
    holds the private key can decrypt as a liveness check, which is what defeats
    replay of a captured document; :func:`decrypt_ciphertext_for_recipient` does
    that half.
    """
    if not document:
        raise NitroTpmError("no attestation document to verify")

    try:
        response = kms_client.generate_random(
            NumberOfBytes=number_of_bytes,
            Recipient={
                "KeyEncryptionAlgorithm": "RSAES_OAEP_SHA_256",
                "AttestationDocument": document,
            },
        )
    except Exception as exc:
        # AccessDenied here is a *verdict*, not a plumbing failure: it is what a
        # PCR condition mismatch looks like. Report it as unverified rather than
        # letting a caller mistake it for a transient error and retry.
        name = type(exc).__name__
        denied = "AccessDenied" in name or "AccessDenied" in str(exc)
        if denied:
            return {
                "verified": False,
                "verifier": "aws-kms",
                "detail": (
                    "KMS refused the attested request. With NitroTPM PCR "
                    "conditions attached to kms:GenerateRandom this is what a "
                    f"measurement mismatch looks like: {exc}"),
            }
        raise NitroTpmError(f"kms:GenerateRandom failed: {exc}") from exc

    ciphertext = response.get("CiphertextForRecipient")
    if not ciphertext:
        # The dangerous case, and the reason this is not a bare try/except.  KMS
        # answers a *non*-attested GenerateRandom happily, just with Plaintext
        # instead.  A caller that only checked for an exception would read that
        # success as a passed attestation.
        return {
            "verified": False,
            "verifier": "aws-kms",
            "detail": (
                "KMS returned Plaintext rather than CiphertextForRecipient, so "
                "it did not treat the request as attested. The document was not "
                "accepted as a valid NitroTPM attestation."),
        }

    return {
        "verified": True,
        "verifier": "aws-kms",
        "detail": (
            "kms:GenerateRandom returned CiphertextForRecipient, which AWS "
            "documents as present only for a valid NitroTPM attestation "
            "document. Trust root is AWS KMS, not a locally pinned "
            "certificate."),
        "ciphertext_for_recipient": ciphertext,
    }


def pcr_conditions(pcr_values: dict, pcrs: Optional[Sequence[int]] = None
                   ) -> dict:
    """Build the ``StringEqualsIgnoreCase`` block for a KMS key policy.

    *pcr_values* maps PCR id (int or str) to a hex digest, as recorded by the
    bake.  Every selected PCR must be present: a policy that silently skips a
    register the operator asked for is weaker than the one they think they have.
    """
    selected = validate_pcr_selection(
        pcrs if pcrs is not None else DEFAULT_PINNED_PCRS)
    normalised = {str(k): v for k, v in (pcr_values or {}).items()}
    out = {}
    for pcr in selected:
        if str(pcr) not in normalised:
            raise NitroTpmError(
                f"PCR{pcr} was selected for pinning but the measurement "
                f"registry has no value for it; re-bake so the capture step "
                f"records it rather than pinning a register you cannot fill")
        out[condition_key(pcr)] = validate_pcr_value(pcr, normalised[str(pcr)])
    return out


#: COSE algorithm identifiers (RFC 8152 §8.1) mapped to their hash.  A real
#: document observed on 2026-08-24 carried ``{1: -35}``, i.e. ES384 -- which
#: matches the P-384 keys AWS uses throughout this chain.
_COSE_ES_ALGS = {-7: "SHA256", -35: "SHA384", -36: "SHA512"}


def parse_document(document: bytes) -> Dict[str, Any]:
    """Decode a NitroTPM attestation document without verifying anything.

    Returns the COSE_Sign1 payload as a dict, with ``nitrotpm_pcrs`` normalised
    to ``{int: lower-case hex}`` so callers can compare against the registry
    without worrying about the raw-bytes representation.

    Separate from :func:`verify_document_locally` so the two can be tested
    apart, and so nothing accidentally reads fields out of a document whose
    signature was never checked -- call this directly only for diagnostics.

    Field names are from a real 5163-byte document produced by
    ``i-093b73bbc84395289`` on 2026-08-24: ``cabundle``, ``certificate``,
    ``digest`` (``"SHA384"``), ``module_id``, ``nitrotpm_pcrs`` (integer keys,
    48-byte values), ``nonce``, ``public_key``, ``timestamp`` (milliseconds) and
    ``user_data``.
    """
    import cbor2

    try:
        cose = cbor2.loads(document)
    except Exception as exc:
        raise NitroTpmError(f"attestation document is not valid CBOR: {exc}")
    # cbor2 surfaces a tagged COSE_Sign1 (tag 18) as CBORTag; untagged
    # documents come back as a bare 4-element array. AWS emits the latter.
    inner = getattr(cose, "value", cose)
    if not isinstance(inner, (list, tuple)) or len(inner) != 4:
        raise NitroTpmError(
            "attestation document is not a COSE_Sign1 4-tuple "
            f"(got {type(inner).__name__})")
    protected, _unprotected, payload_bytes, signature = inner
    try:
        payload = cbor2.loads(payload_bytes)
    except Exception as exc:
        raise NitroTpmError(f"COSE payload is not valid CBOR: {exc}")
    if not isinstance(payload, dict):
        raise NitroTpmError("COSE payload is not a map")

    pcrs = {}
    for key, value in (payload.get("nitrotpm_pcrs") or {}).items():
        if isinstance(value, (bytes, bytearray)):
            pcrs[int(key)] = bytes(value).hex()
    payload["nitrotpm_pcrs"] = pcrs
    payload["_protected"] = protected
    payload["_payload_bytes"] = payload_bytes
    payload["_signature"] = signature
    return payload


def verify_document_locally(document: bytes, root_pem: str, *,
                            expected_pcrs: Optional[Dict[Any, str]] = None,
                            expected_user_data: Optional[bytes] = None,
                            now=None) -> Dict[str, Any]:
    """Verify a NitroTPM attestation document against a pinned AWS root.

    This exists because the older comment here -- that ``certs/nitro-root.pem``
    "endorses a different key hierarchy" and so a NitroTPM document could only
    be checked by delegating to KMS -- was **wrong**, and it was the stated
    reason ``gpu-cc-aws`` reported its CPU evidence as unverified.

    Measured on 2026-08-24 against a real document: the ``cabundle`` roots at
    ``CN=aws.nitro-enclaves``, byte-for-byte the certificate this repository
    already pins for ``nitro-aws``
    (``sha256=641a0321a3e244efe456463195d606317ed7cdcc3c1756e09893f3c68f79bb5b``).
    The chain is TPM leaf -> instance -> zonal -> region -> root, five
    certificates, every link's signature valid, and the COSE_Sign1 signature
    verifies under the TPM leaf's P-384 key.  So the trust root stays in this
    repository and the client needs no AWS credentials at all.

    :func:`verify_document_via_kms` remains useful as an *independent* opinion
    and is still what enforces measured boot for key release, where the
    condition keys do the work.  It is not required to verify a document.

    Revocation is deliberately not checked, matching the existing ``nitro-aws``
    client and AWS's own guidance that CRL checking be disabled when validating
    Nitro attestation documents; the pinned root carries no CRL distribution
    point to follow.

    Returns the verified payload.  Raises :class:`NitroTpmError` on any failure,
    because a partially-verified attestation is not a useful return value.
    """
    import datetime

    from cryptography import x509
    from cryptography.hazmat.backends import default_backend
    from cryptography.hazmat.primitives import hashes, serialization
    from cryptography.hazmat.primitives.asymmetric import ec, padding, utils

    import cbor2

    payload = parse_document(document)
    if not (root_pem or "").strip():
        raise NitroTpmError(
            "no pinned AWS Nitro root certificate supplied; refusing to "
            "'verify' a document against nothing")

    root_ca = x509.load_pem_x509_certificate(
        root_pem.strip().encode("utf-8"), default_backend())
    leaf_der = payload.get("certificate")
    cabundle = list(payload.get("cabundle") or [])
    if not leaf_der:
        raise NitroTpmError("attestation document carries no leaf certificate")

    # AWS orders cabundle [ROOT, INTERM_1, ..., INTERM_N]; reversing it and
    # prepending the leaf yields [LEAF, ..., ROOT], the order to walk.
    leaf = x509.load_der_x509_certificate(leaf_der, default_backend())
    chain = [leaf] + [x509.load_der_x509_certificate(c, default_backend())
                      for c in reversed(cabundle)]

    moment = now or datetime.datetime.now(datetime.timezone.utc)
    for index, cert in enumerate(chain):
        if not (cert.not_valid_before_utc <= moment <= cert.not_valid_after_utc):
            label = "leaf" if index == 0 else f"chain[{index}]"
            raise NitroTpmError(
                f"{label} certificate is outside its validity window "
                f"({cert.not_valid_before_utc} to {cert.not_valid_after_utc})")

    for index in range(len(chain) - 1):
        subject, issuer = chain[index], chain[index + 1]
        if subject.issuer != issuer.subject:
            raise NitroTpmError(
                f"certificate chain broken at link {index}: issuer name "
                f"does not match the next subject")
        pub = issuer.public_key()
        try:
            if isinstance(pub, ec.EllipticCurvePublicKey):
                pub.verify(subject.signature, subject.tbs_certificate_bytes,
                           ec.ECDSA(subject.signature_hash_algorithm))
            else:
                pub.verify(subject.signature, subject.tbs_certificate_bytes,
                           padding.PKCS1v15(),
                           subject.signature_hash_algorithm)
        except Exception as exc:
            raise NitroTpmError(
                f"certificate signature invalid at link {index}: {exc}")

    top = chain[-1].public_bytes(serialization.Encoding.PEM)
    if top != root_ca.public_bytes(serialization.Encoding.PEM):
        raise NitroTpmError(
            "top of the attestation chain is not the pinned AWS Nitro root; "
            "refusing a chain that ends somewhere else")

    alg = None
    try:
        alg = cbor2.loads(payload["_protected"]).get(1)
    except Exception:
        pass
    hash_name = _COSE_ES_ALGS.get(alg)
    if hash_name is None:
        raise NitroTpmError(
            f"unsupported or absent COSE algorithm in protected header: {alg!r}")

    sig_structure = cbor2.dumps(
        ["Signature1", payload["_protected"], b"", payload["_payload_bytes"]])
    signature = payload["_signature"]
    leaf_pub = leaf.public_key()
    if not isinstance(leaf_pub, ec.EllipticCurvePublicKey):
        raise NitroTpmError(
            f"leaf key is {type(leaf_pub).__name__}, expected an EC key")
    half = len(signature) // 2
    der_sig = utils.encode_dss_signature(
        int.from_bytes(signature[:half], "big"),
        int.from_bytes(signature[half:], "big"))
    try:
        leaf_pub.verify(der_sig, sig_structure,
                        ec.ECDSA(getattr(hashes, hash_name)()))
    except Exception as exc:
        raise NitroTpmError(f"COSE_Sign1 signature does not verify: {exc}")

    # Only now is anything in the payload worth reading.
    if expected_pcrs:
        observed = payload["nitrotpm_pcrs"]
        for key, want in expected_pcrs.items():
            pcr_id = int(str(key).replace("PCR", ""))
            got = observed.get(pcr_id, "")
            if got.lower() != str(want).lower():
                raise NitroTpmError(
                    f"PCR{pcr_id} mismatch: expected {want}, got "
                    f"{got or '(absent)'}")

    if expected_user_data is not None:
        got = payload.get("user_data")
        got = bytes(got) if isinstance(got, (bytes, bytearray)) else b""
        if got != expected_user_data:
            raise NitroTpmError(
                "user_data does not match the expected channel binding "
                f"(expected {expected_user_data.hex()}, got "
                f"{got.hex() or '(absent)'})")

    return payload


__all__ = [
    "NITRO_TPM_ATTEST_BIN",
    "DEFAULT_PINNED_PCRS",
    "PCR_BOOT_MANAGER_CODE",
    "PCR_SECURE_BOOT_POLICY",
    "PCR_KERNEL_CMDLINE",
    "NitroTpmError",
    "attestation_document",
    "condition_key",
    "parse_document",
    "verify_document_locally",
    "verify_document_via_kms",
    "decrypt_ciphertext_for_recipient",
    "generate_recipient_keypair",
    "pcr_conditions",
    "read_pcrs",
    "validate_pcr_selection",
    "validate_pcr_value",
]
