import socket
import json
import logging
import subprocess
import base64
import traceback

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

VSOCK_PORT = 5005

# ==========================================
# USER IMPORTS (Generated by AI)
# ==========================================
{user_imports}

# ==========================================
# USER LOGIC (Generated by AI)
# ==========================================
def process_request(data):
    """
    Processes the payload from the client.
    Input 'data' can be a dictionary (single item) or a list (batch), 
    depending on what the client sends.
    Returns the processed result (dict or list).
    """
{user_logic}

# ==========================================

import os
from cryptography.hazmat.primitives.asymmetric import rsa, padding
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from asn1crypto import cms as asn1_cms, core as asn1_core
import boto3
from botocore.config import Config
import threading

# Generate RSA keypair for KMS Attestation on startup
_RSA_KEY = rsa.generate_private_key(public_exponent=65537, key_size=2048)
_RSA_PUB = _RSA_KEY.public_key().public_bytes(
    encoding=serialization.Encoding.DER,
    format=serialization.PublicFormat.SubjectPublicKeyInfo
)
_RSA_PUB_B64 = base64.b64encode(_RSA_PUB).decode('utf-8')
_entropy_seeded = False

def seed_entropy_from_kms():
    """Supplement enclave entropy with KMS GenerateRandom (called once after creds arrive)."""
    global _entropy_seeded
    if _entropy_seeded:
        logging.info("[ENTROPY] Already seeded, skipping")
        return
    try:
        region = os.environ.get('AWS_REGION', 'us-east-2')
        logging.info(f"[ENTROPY] Calling KMS GenerateRandom in region={region}...")
        kms_config = Config(
            connect_timeout=10, read_timeout=30,
            retries={'max_attempts': 1, 'mode': 'standard'}
        )
        client = boto3.client('kms', region_name=region, config=kms_config)
        resp = client.generate_random(NumberOfBytes=256)
        with open('/dev/urandom', 'wb') as f:
            f.write(resp['Plaintext'])
        _entropy_seeded = True
        logging.info("[ENTROPY] Seeded entropy pool with 256 bytes from KMS GenerateRandom")
    except Exception as e:
        logging.warning(f"[ENTROPY] KMS GenerateRandom failed (non-fatal): {type(e).__name__}: {e}")
        logging.warning(traceback.format_exc())

def _bring_up_loopback():
    """Bring up the loopback interface so 127.0.0.1 is routable."""
    for cmd in [
        ['ip', 'link', 'set', 'lo', 'up'],
        ['ip', 'addr', 'add', '127.0.0.1/8', 'dev', 'lo'],
    ]:
        try:
            subprocess.run(cmd, capture_output=True, timeout=5)
        except Exception:
            pass
    try:
        test = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        test.settimeout(2)
        test.bind(('127.0.0.1', 0))
        test.close()
        logging.info("Loopback interface is up")
    except Exception as e:
        logging.warning(f"Loopback may not be functional: {e}")

def start_vsock_proxy():
    """
    TCP-to-VSOCK tunnel on 127.0.0.1:443 -> vsock CID 3 port 8000.
    The host's vsock-proxy (simple mode) forwards vsock:8000 directly to
    kms.<region>.amazonaws.com:443.  We patch DNS so boto3 resolves the
    KMS hostname to 127.0.0.1, giving it a direct TLS path to KMS with
    proper certificate verification -- no HTTP CONNECT needed.
    """
    _bring_up_loopback()

    _orig_getaddrinfo = socket.getaddrinfo
    def _patched_getaddrinfo(host, port, *args, **kwargs):
        if isinstance(host, str) and host.startswith('kms.') and host.endswith('.amazonaws.com'):
            logging.info(f"DNS redirect: {host}:{port} -> 127.0.0.1:{port}")
            return _orig_getaddrinfo('127.0.0.1', port, *args, **kwargs)
        return _orig_getaddrinfo(host, port, *args, **kwargs)
    socket.getaddrinfo = _patched_getaddrinfo

    def _forward(src, dst, label):
        """Forward data in one direction using blocking recv (no select)."""
        try:
            while True:
                data = src.recv(65536)
                if not data:
                    break
                dst.sendall(data)
        except Exception:
            pass
        finally:
            for s in (src, dst):
                try:
                    s.shutdown(socket.SHUT_RDWR)
                except Exception:
                    pass
                try:
                    s.close()
                except Exception:
                    pass

    def _accept_loop():
        srv = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        srv.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        srv.bind(('127.0.0.1', 443))
        srv.listen(8)
        logging.info("TCP-to-VSOCK proxy listening on 127.0.0.1:443")
        while True:
            try:
                tcp_sock, _ = srv.accept()
                vsock_sock = socket.socket(socket.AF_VSOCK, socket.SOCK_STREAM)
                vsock_sock.settimeout(10)
                vsock_sock.connect((3, 8000))
                vsock_sock.settimeout(None)
                logging.info("VSOCK tunnel established to CID 3:8000")
                threading.Thread(target=_forward, args=(tcp_sock, vsock_sock, "tcp→vsock"), daemon=True).start()
                threading.Thread(target=_forward, args=(vsock_sock, tcp_sock, "vsock→tcp"), daemon=True).start()
            except Exception as e:
                logging.error(f"Proxy connect error: {e}")
                try:
                    tcp_sock.close()
                except Exception:
                    pass

    threading.Thread(target=_accept_loop, daemon=True).start()

    import time
    time.sleep(0.5)

    os.environ['AWS_DEFAULT_REGION'] = os.environ.get('AWS_REGION', 'us-east-2')
    logging.info("Started vsock proxy (simple TCP tunnel, no HTTP CONNECT)")

def handle_attestation_request(nonce: str = "", public_key_b64: str = "") -> str:
    try:
        logging.info("Calling nsm-cli for attestation document")
        args = ['/usr/local/bin/nsm-cli']
        if nonce:
            args.extend(['--nonce', nonce])
        if public_key_b64:
            args.extend(['--public-key', public_key_b64])
            
        result = subprocess.run(args, capture_output=True, text=True, check=True)
        return result.stdout.strip()
    except subprocess.CalledProcessError as e:
        logging.error(f"Attestation failed: {e.stderr}")
        return json.dumps({"error": "Attestation tool is not available or failed"})

def _decrypt_cms_enveloped_data(cms_bytes: bytes, private_key) -> bytes:
    """
    Parses CMS (RFC 5652) EnvelopedData returned by KMS CiphertextForRecipient,
    RSA-unwraps the content-encryption key, then AES-decrypts the payload.
    """
    logging.info(f"[CMS] Envelope size: {len(cms_bytes)} bytes")
    content_info = asn1_cms.ContentInfo.load(cms_bytes)
    logging.info(f"[CMS] ContentInfo type: {content_info['content_type'].native}")
    enveloped_data = content_info['content']

    ri = enveloped_data['recipient_infos'][0].chosen
    encrypted_key = ri['encrypted_key'].native
    logging.info(f"[CMS] Encrypted CEK size: {len(encrypted_key)} bytes")

    cek = private_key.decrypt(
        encrypted_key,
        padding.OAEP(
            mgf=padding.MGF1(algorithm=hashes.SHA256()),
            algorithm=hashes.SHA256(),
            label=None
        )
    )
    logging.info(f"[CMS] Decrypted CEK size: {len(cek)} bytes")

    enc_ci = enveloped_data['encrypted_content_info']
    algo = enc_ci['content_encryption_algorithm']
    encrypted_content = enc_ci['encrypted_content'].native

    algo_name = algo['algorithm'].native
    algo_oid = algo['algorithm'].dotted
    mode = algo.encryption_mode
    iv_or_nonce = algo.encryption_iv
    logging.info(f"[CMS] Algorithm: {algo_name} (OID {algo_oid}), mode={mode}, "
                 f"iv/nonce={len(iv_or_nonce)} bytes, ciphertext={len(encrypted_content)} bytes")

    if mode == 'gcm':
        plaintext = AESGCM(cek).decrypt(iv_or_nonce, encrypted_content, None)
    elif mode == 'cbc':
        decryptor = Cipher(algorithms.AES(cek), modes.CBC(iv_or_nonce)).decryptor()
        padded = decryptor.update(encrypted_content) + decryptor.finalize()
        plaintext = padded[:-padded[-1]]
    else:
        raise ValueError(f"Unsupported encryption mode '{mode}' for algorithm {algo_name} (OID {algo_oid})")

    logging.info(f"[CMS] Decrypted plaintext size: {len(plaintext)} bytes")
    return plaintext

def kms_decrypt_with_attestation(ciphertext_b64: str, region: str = None) -> bytes:
    """
    Decrypts KMS ciphertext using AWS Nitro Enclave Attestation.
    Requests an attestation document with the enclave's generated public key,
    passes it to KMS, and unwraps the CMS envelope returned in CiphertextForRecipient.
    """
    logging.info("[KMS_DECRYPT] Step 1: Requesting attestation doc with RSA public key...")
    doc_b64 = handle_attestation_request(public_key_b64=_RSA_PUB_B64)
    logging.info(f"[KMS_DECRYPT] Attestation doc length: {len(doc_b64)} chars")
    if "error" in doc_b64:
        raise Exception(f"Failed to get attestation doc for KMS: {doc_b64}")
        
    doc_bytes = base64.b64decode(doc_b64)
    ciphertext_bytes = base64.b64decode(ciphertext_b64)
    logging.info(f"[KMS_DECRYPT] Step 2: Attestation doc: {len(doc_bytes)} bytes, ciphertext: {len(ciphertext_bytes)} bytes")
    
    if not region:
        region = os.environ.get('AWS_REGION', 'us-east-2')
        
    logging.info(f"[KMS_DECRYPT] Step 3: Calling KMS Decrypt in region={region}")
    
    kms_config = Config(
        connect_timeout=10,
        read_timeout=60,
        retries={'max_attempts': 2, 'mode': 'standard'}
    )
    client = boto3.client('kms', region_name=region, config=kms_config)
    
    response = client.decrypt(
        CiphertextBlob=ciphertext_bytes,
        Recipient={
            'KeyEncryptionAlgorithm': 'RSAES_OAEP_SHA_256',
            'AttestationDocument': doc_bytes
        }
    )
    
    cfr = response.get('CiphertextForRecipient')
    pt = response.get('Plaintext')
    logging.info(f"[KMS_DECRYPT] Step 4: KMS response keys={list(response.keys())}")
    logging.info(f"[KMS_DECRYPT]   CiphertextForRecipient: {type(cfr).__name__}, len={len(cfr) if cfr else 0}")
    logging.info(f"[KMS_DECRYPT]   Plaintext: {type(pt).__name__}, len={len(pt) if pt else 0}")
    
    if not cfr or len(cfr) == 0:
        raise Exception(f"KMS returned empty CiphertextForRecipient. Plaintext len={len(pt) if pt else 0}. "
                        f"This may mean the Recipient/attestation was ignored by KMS.")
    
    logging.info("[KMS_DECRYPT] Step 5: Unwrapping CMS envelope...")
    plaintext = _decrypt_cms_enveloped_data(cfr, _RSA_KEY)
    logging.info(f"[KMS_DECRYPT] Step 6: Done. Plaintext size: {len(plaintext)} bytes")
    return plaintext

def run_vsock_server():
    start_vsock_proxy()
    
    server_sock = socket.socket(socket.AF_VSOCK, socket.SOCK_STREAM)
    server_sock.bind((socket.VMADDR_CID_ANY, VSOCK_PORT))
    server_sock.listen(5)
    logging.info(f"Listening on vsock port {VSOCK_PORT}")

    # One-time startup report for build provenance audit (stdout so nitro-cli console captures it)
    try:
        startup_report = {
            "audit": "enclave_startup",
            "steps": [
                "rsa_key_generated",
                "loopback_interface_up",
                "dns_patch_kms_to_loopback",
                "tcp_to_vsock_proxy_listening",
                "vsock_server_listening",
            ],
        }
        print(json.dumps(startup_report), flush=True)
    except Exception:
        pass

    while True:
        client_sock, addr = server_sock.accept()
        logging.info(f"Client connected: {addr}")
        try:
            payload = b""
            while True:
                chunk = client_sock.recv(4096)
                if not chunk: break
                payload += chunk
            
            if not payload: continue
            logging.info(f"[VSOCK] Received payload: {len(payload)} bytes")
            
            data = json.loads(payload.decode('utf-8'))
            data_keys = list(data.keys()) if isinstance(data, dict) else f"list[{len(data)}]"
            logging.info(f"[VSOCK] Parsed JSON, keys/type: {data_keys}")
            
            # Extract and configure AWS credentials if provided by the host proxy
            aws_creds = data.pop('__aws_credentials', None)
            if aws_creds:
                os.environ['AWS_ACCESS_KEY_ID'] = aws_creds.get('access_key', '')
                os.environ['AWS_SECRET_ACCESS_KEY'] = aws_creds.get('secret_key', '')
                if aws_creds.get('token'):
                    os.environ['AWS_SESSION_TOKEN'] = aws_creds['token']
                if aws_creds.get('region'):
                    os.environ['AWS_REGION'] = aws_creds['region']
                    os.environ['AWS_DEFAULT_REGION'] = aws_creds['region']
                logging.info(f"[VSOCK] AWS credentials configured, region={aws_creds.get('region')}")
            else:
                logging.warning("[VSOCK] No __aws_credentials in payload!")
            
            # 1. Attestation Path
            if isinstance(data, dict) and data.get("action") == "get_attestation":
                logging.info("[VSOCK] -> Attestation path")
                doc_b64 = handle_attestation_request(data.get("nonce", ""))
                response = json.dumps({"attestation_doc_b64": doc_b64})
            
            # 2. Data Processing Path
            else:
                logging.info("[VSOCK] -> Data processing path")
                seed_entropy_from_kms()
                ciphertext_b64 = data.get("ciphertext_b64") if isinstance(data, dict) else None
                if not ciphertext_b64:
                    raise ValueError("Data path requires 'ciphertext_b64' in payload")
                logging.info("[VSOCK] Decrypting ciphertext via KMS attestation...")
                plaintext_bytes = kms_decrypt_with_attestation(ciphertext_b64)
                plaintext_obj = json.loads(plaintext_bytes.decode("utf-8"))
                logging.info("[VSOCK] Entropy seeding done, calling process_request...")
                results = process_request(plaintext_obj)
                logging.info(f"[VSOCK] process_request returned type={type(results).__name__}")
                response = json.dumps(results, default=str)
                logging.info(f"[VSOCK] Response JSON size: {len(response)} bytes")
                
            client_sock.sendall(response.encode('utf-8'))
            logging.info("[VSOCK] Response sent successfully")
            
        except Exception as e:
            tb = traceback.format_exc()
            logging.error(f"Error processing request: {e}")
            logging.error(tb)
            error_detail = {
                "error": "Internal enclave processing error",
                "exception": str(e),
                "exception_type": type(e).__name__,
                "traceback": tb
            }
            client_sock.sendall(json.dumps(error_detail).encode('utf-8'))
        finally:
            client_sock.close()

if __name__ == "__main__":
    run_vsock_server()